### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by Olga-Skoroded** [alyonafomenkova/fsd-test-2#12]
Использовать деструктуризацию параметров pug миксинов

**Comment by Olga-Skoroded** [comment]
Все инклюды размещать в начале файла

**Comment by Olga-Skoroded** [comment]
Названия папки, файла, миксина и возвращаемого блока должны совпадать
![bullet naming](https://user-images.githubusercontent.com/68814270/93047894-be2f2500-f687-11ea-8009-7c53584314ae.png)

**Comment by Olga-Skoroded** [comment]
Тут излишне создавать переменную settings, можно же просто задать дефолтное значение для items)
![bullet list](https://user-images.githubusercontent.com/68814270/93047972-efa7f080-f687-11ea-9ab1-1cfa9bba7527.png)

**Comment by Olga-Skoroded** [comment]
Нужно использовать шаблонные строки вместо конкатенации 
![concat](https://user-images.githubusercontent.com/68814270/93050998-00f3fb80-f68e-11ea-81e5-c3939aac871c.png)

**Comment by Olga-Skoroded** [comment]
Может когда данных очень много их лучше в json выносить? 
![form-elements](https://user-images.githubusercontent.com/68814270/94019192-b126da00-fddb-11ea-92c6-9d824748451d.png)

**Comment by alyonafomenkova** [comment]
Вынесла данные в отдельные json, если переменных больше двух.

**Comment by Olga-Skoroded** [comment]
Тут тоже конкатенацию на шаблонные строки поменять)
![concat](https://user-images.githubusercontent.com/68814270/94813798-aa731500-0422-11eb-9b40-a6be783484db.png)

**Comment by Olga-Skoroded** [comment]
Инкремент / декремент не используем, меняем на запись вида num += 1 [airbnb](https://github.com/airbnb/javascript#variables--unary-increment-decrement)
![plusplus](https://user-images.githubusercontent.com/68814270/94813949-e0b09480-0422-11eb-9a69-313fa1f43b57.png)
