### ISSUE TITLE
favicon 

### ISSUE THREAD

**Issue by Olga-Skoroded** [alyonafomenkova/fsd-test-2#19]
> В сафари своя версия favicon, ее тоже обязательно надо настраивать. 
То есть нужна svg для контура иконки, и нужен цвет для иконки при наведении. [Статья](https://yoast.com/dev-blog/safari-pinned-tab-icon-mask-icon/)
[(best-practices)](https://github.com/fullstack-development/front-end-best-practices/tree/master/HTML#3.3)

**Comment by alyonafomenkova** [comment]
![image](https://user-images.githubusercontent.com/29568698/95013699-a9bcc780-064a-11eb-866d-a4c0e74a5663.png)
