### ISSUE TITLE
Разметка

### ISSUE THREAD

**Issue by AkhmadBabaev** [alyonafomenkova/fsd-test-2#23]
https://github.com/alyonafomenkova/fsd-test-2/blob/d3bdb6a3495d94e2fbb23f1ccd31d0f6ea95ba8b/src/pages/details/details.pug#L10-L12

Предпочтительнее использовать одинарные кавычки при работе с JS, CSS. В pug так же присуствует js кода и когда ты настроишь eslint на валидацию pug файлов вылезет много ошибок. Используй двойные кавычки для указания значения в виде литерала атрибутов html тэгов. 

Вот пример использования одинарных и двойных кавычек `<div class="name" id=getID('user')>`.

**Comment by AkhmadBabaev** [comment]
https://github.com/alyonafomenkova/fsd-test-2/blob/d3bdb6a3495d94e2fbb23f1ccd31d0f6ea95ba8b/src/pages/details/details.pug#L25-L28

Стили через атрибуты обычно передают когда другого варианта нет, как например для положения ползунка в слайдере. А так же слово Photo в тэге img не стоит использовать так как экранная читался определив тэг img сообщит что это изображение )

**Comment by alyonafomenkova** [comment]
обсудили с @AkhmadBabaev и решили, что минимальные стили (например, размеры) через атрибуты ещё можно добавлять встроенным svg и контентным изображениям

**Comment by AkhmadBabaev** [comment]
https://github.com/alyonafomenkova/fsd-test-2/blob/2cbf737225a79f6b7062a4a7913372077861466d/src/components/button/button.pug#L3-L25

Можно упростить способ установки модификаторов, [тут подсказка как это сделать](https://github.com/AkhmadBabaev/toxin-demo/issues/13).

**Comment by AkhmadBabaev** [comment]
В pug компонентах не вижу дефолтных значений для параметров компонентов, добавь дефолты туда где это допустимо, к примеру для компонента Rating.

**Comment by AkhmadBabaev** [comment]
https://github.com/alyonafomenkova/fsd-test-2/blob/2cbf737225a79f6b7062a4a7913372077861466d/src/assets/favicons/site.webmanifest#L3-L15

Неверный путь и иконкам, иконки находятся по пути /assets/favicons.
