### ISSUE TITLE
Самодостаточность блоков.

### ISSUE THREAD

**Issue by prodderman** [alyonafomenkova/fsd-test-2#28]
https://github.com/alyonafomenkova/fsd-test-2/blob/dd11f837b7402d4dfae505228218d41c7c06129c/src/pages/search/search.scss#L4-L6

Тут и практически во всех страницах нарушается самодостаточность блоков.

Блок не должен знать, что он будет использоваться во флекс-контейнере. И наоборот, блоки использующие этот блок не должны знать, что его нужно использовать как флекс-элемент.

**Comment by alyonafomenkova** [comment]
На мой взгляд, уместно добавить глобально `main` для растяжения контента.
К тому же в `html`, `body` уже есть часть стилей, необходимых, чтобы прижать футер к низу страницы. 
И ещё в стандартах есть отсылка к [статье](https://dimox.name/press_footer_bottom_with_css/), там тоже подобные стили вынесены глобально.
