### ISSUE TITLE
Стили

### ISSUE THREAD

**Issue by Olga-Skoroded** [alyonafomenkova/fsd-test-2#6]
В качестве единиц измерения лучше использовать rem'ы, т.к. изменив размер шрифта одного элемента, можно будет изменить масштаб всей верстки

**Comment by Olga-Skoroded** [comment]
В стилевых файлах использовать одинарные кавычки

**Comment by Olga-Skoroded** [comment]
> Прописывать дефолтный цвет фона, цвет шрифта, font-size и семейство шрифта у html;
Далее размер шрифта будет ориентиром для всех элементов, у которых используется rem для единиц измерения кегля.
[(best practies)](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/rules.md)

**Comment by alyonafomenkova** [comment]
> В качестве единиц измерения лучше использовать rem'ы, т.к. изменив размер шрифта одного элемента, можно будет изменить масштаб всей верстки

px оставила только в base.scss:
- разумеется, у html 
- в специальном классе visually-hidden
- у переменных с шириной для наглядности

**Comment by Olga-Skoroded** [comment]
Не нужно постоянно дублировать родительский селектор, sass позволяет создавать вложенность и обращаться к внешнему селектору при помощи амперсанда (можно почитать в [документации](https://sass-lang.com/documentation/style-rules/parent-selector))

**Comment by Olga-Skoroded** [comment]
Думаю, vissually-hidden тоже лучше миксином сделать

**Comment by Olga-Skoroded** [comment]
Можно сделать миксин для `@font-face` правил, чтобы сократить количество дублирующегося кода

**Comment by alyonafomenkova** [comment]
> Не нужно постоянно дублировать родительский селектор, sass позволяет создавать вложенность и обращаться к внешнему селектору при помощи амперсанда (можно почитать в [документации](https://sass-lang.com/documentation/style-rules/parent-selector))

Применила амперсанд с учётом уровня вложенности селекторов (чтобы вложенность не была больше двух).

**Comment by Olga-Skoroded** [comment]
Глобальные стили допускаются только для body и html

**Comment by Olga-Skoroded** [comment]
Sass миксины лучше вынести в отдельный файл

**Comment by Olga-Skoroded** [comment]
Тут в стилях для expandable-checkbox переопределяются стили для checkbox__list. Все стили компонента должны лежать в одном месте, нельзя переопределять их извне 
![инкапсуляция](https://user-images.githubusercontent.com/68814270/92342668-af76ca00-f0eb-11ea-9121-0265ad403cfd.png)

**Comment by Olga-Skoroded** [comment]
Отбивай стили для элементов пустой строкой, так легче читать)
![пустая строка](https://user-images.githubusercontent.com/68814270/92342680-b998c880-f0eb-11ea-8e14-ed7d9c7734e2.png)

**Comment by alyonafomenkova** [comment]
> Sass миксины лучше вынести в отдельный файл

Вынесла все миксины в отдельный файл, кроме `setupFont`. Нагляднее, если он будет в файле шрифтов, тем более сам файл маленький

**Comment by Olga-Skoroded** [comment]
Можно использовать амперсанд даже если блоку не заданы стили) 
![bullet styles](https://user-images.githubusercontent.com/68814270/93051089-22ed7e00-f68e-11ea-92b8-0e1902a0e122.png)

**Comment by Olga-Skoroded** [comment]
В таких случаях
![amper](https://user-images.githubusercontent.com/68814270/93051810-41a04480-f68f-11ea-86a6-222fc1bb6e1a.png)
будет лучше писать вот так
![dropdown](https://user-images.githubusercontent.com/68814270/93051875-5d0b4f80-f68f-11ea-8b3e-8fa521edead6.png)
