### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by Olga-Skoroded** [alyonafomenkova/fsd-test-2#7]
**Календарь**
1. Тут какие-то странные стили у даты 
![calendar hover](https://user-images.githubusercontent.com/68814270/91683939-2c4ff400-eb80-11ea-9f45-a4eae81e23e2.png)
2. У чисел внутри диапазона не должно быть ховер эффекта
3. Не должно быть кнопки "очистить", если не выбран диапазон

**Comment by Olga-Skoroded** [comment]
Это у date dropdown и filter date dropdown поправить) 
> Добавлять элементу cursor: pointer, если он кликабелен и по умолчанию этого не поддерживает;

**Comment by Olga-Skoroded** [comment]
При клике вне дропдауна он должен закрываться

**Comment by Olga-Skoroded** [comment]
Тут заголовок при checked должен быть темнее 
![checkbox](https://user-images.githubusercontent.com/68814270/91684337-65d52f00-eb81-11ea-81de-48f8402b657c.png)

**Comment by alyonafomenkova** [comment]
> Тут заголовок при checked должен быть темнее
> ![checkbox](https://user-images.githubusercontent.com/68814270/91684337-65d52f00-eb81-11ea-81de-48f8402b657c.png)

@Olga-Skoroded Заголовок должен быть темнее не только при checked. Поправила.

**Comment by Olga-Skoroded** [comment]
Тоже должен закрываться, если кликнуть за его пределами) 
![checkbox list](https://user-images.githubusercontent.com/68814270/92198090-b7412f00-ee9d-11ea-90f2-41f2472f87ec.png)

**Comment by Olga-Skoroded** [comment]
Гамбургер меню странно выглядит при раскрытии) 
![menu](https://user-images.githubusercontent.com/68814270/93052217-e6bb1d00-f68f-11ea-8ea4-a7bc3432a9c2.png)
