### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by Olga-Skoroded** [alyonafomenkova/fsd-test-2#9]
Для добавления модификатора использовать одно нижнее подчеркивание: 
- `имя-блока_имя-модификатора` 
- `имя-блока__имя-элемента_имя-модификатора`

**Comment by Olga-Skoroded** [comment]
Нужно использовать модификатор типа ключ-значение. Почитай [вот здесь](https://ru.bem.info/methodology/quick-start/#%D0%BC%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80) и проверь по всему проекту пожалуйста) 
![modif](https://user-images.githubusercontent.com/68814270/92199814-56682580-eea2-11ea-8c12-3ebdca974ef5.png)

**Comment by alyonafomenkova** [comment]
неклассическое правило именования модификаторов (через --) остались у компонентов:
- range-slider
- date-dropdown
т.к. такой стиль выбран в исходных файлах сторонних плагинов

**Comment by alyonafomenkova** [comment]
Мне не особо нравятся модификаторы вроде `&_margin_bottom-10`.
Правильнее было бы `&_bottom-indent_size-s`. Но из-за PixelPerfect значений получается немало, поэтому в данном случае с цифрами нагляднее.

**Comment by Olga-Skoroded** [comment]
Название папки, файла, миксина и возвращаемого блока должна совпадать
![bullet naming](https://user-images.githubusercontent.com/68814270/93047927-d56e1280-f687-11ea-8356-8e09d8a8d4a8.png)

**Comment by Olga-Skoroded** [comment]
Нельзя задавать внешнюю геометрию блокам 
![cards](https://user-images.githubusercontent.com/68814270/94018891-4b3a5280-fddb-11ea-8a5f-66bada92828a.png)

**Comment by alyonafomenkova** [comment]
> Нельзя задавать внешнюю геометрию блокам
> ![cards](https://user-images.githubusercontent.com/68814270/94018891-4b3a5280-fddb-11ea-8a5f-66bada92828a.png)

Я нигде не задаю внешнюю геометрию компонентам.
В данном случае cards - не компонент, а самодостаточная страница, cards существует только здесь и нигде больше не используется. Поэтому, на мой взгляд, здесь уместно задавать внешнюю геометрию.

**Comment by Olga-Skoroded** [comment]
Тут на кнопке смешано две сущности dropdown__button и dropdown__decrement-button, по best-practices миксы использовать нельзя) 
![mix](https://user-images.githubusercontent.com/68814270/94815287-916b6380-0424-11eb-935a-8c23e2eee557.png)

**Comment by Olga-Skoroded** [comment]
Мне кажется, в случае с переключением видимости элемента, правильнее использовать булевый модификатор opened, visible и т.п.  
![modif opened](https://user-images.githubusercontent.com/68814270/95212382-d5d97380-0817-11eb-9991-37a3d7c5b911.png)

**Comment by alyonafomenkova** [comment]
Для иконок `.header__toggle-menu-icon_state_opened`, `.header__toggle-menu-icon_state_closed` оставила модификаторы ключ-значение, т.к. это две разные иконки. Решила их переименовать в `header__toggle-menu-icon_view_hamburger` и `header__toggle-menu-icon_view_arrow`, чтобы названия не сбивали с толку.
В других местах поменяла модификаторы на булевые.
